# Generated by Django 5.1.4 on 2026-07-01 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DataRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "requested_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Date de création de la demande."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Reçue"),
                            ("processing", "En cours"),
                            ("completed", "Répondue"),
                        ],
                        default="received",
                        help_text="État de traitement de la demande.",
                        max_length=20,
                    ),
                ),
                (
                    "responded_at",
                    models.DateTimeField(
                        blank=True, help_text="Date de réponse à la demande.", null=True
                    ),
                ),
                (
                    "export_hash",
                    models.CharField(
                        blank=True, help_text="Hash SHA-256 du fichier exporté.", max_length=64
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Demande d'export",
                "verbose_name_plural": "Demandes d'export",
            },
        ),
    ]
