# Generated by Django 5.1.4 on 2026-07-02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_datarequest_auditevent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TeacherSuggestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "author",
                    models.ForeignKey(
                        help_text="Professeur à l'origine de la suggestion.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="written_teacher_suggestions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        help_text="Élève destinataire de la suggestion.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_teacher_suggestions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Suggestion pédagogique",
                "verbose_name_plural": "Suggestions pédagogiques",
                "ordering": ["-created_at"],
            },
        ),
    ]