# Generated by Django 5.1.4 on 2026-06-30 16:04

from django.db import migrations, models


def set_existing_quizzes_completed(apps, schema_editor):
    Quiz = apps.get_model("quizzes", "Quiz")
    Quiz.objects.all().update(status="completed", progress_step=5)


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0002_question_selected_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="error_message",
            field=models.TextField(
                blank=True, default="", help_text="Message d'erreur en cas d'échec."
            ),
        ),
        migrations.AddField(
            model_name="quiz",
            name="progress_step",
            field=models.PositiveIntegerField(
                default=0, help_text="Étape actuelle de la génération (0 à 5)."
            ),
        ),
        migrations.AddField(
            model_name="quiz",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "En attente"),
                    ("processing", "Génération en cours"),
                    ("completed", "Généré"),
                    ("failed", "Échec"),
                ],
                default="pending",
                help_text="Statut de la génération du quiz.",
                max_length=20,
            ),
        ),
        migrations.RunPython(set_existing_quizzes_completed),
    ]
