# Generated by Django 5.1.4 on 2026-06-30 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0003_quiz_error_message_quiz_progress_step_quiz_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quiz",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "En attente"),
                    ("processing", "Génération en cours"),
                    ("completed", "Généré"),
                    ("failed", "Échec"),
                ],
                default="completed",
                help_text="Statut de la génération du quiz.",
                max_length=20,
            ),
        ),
    ]
