# Generated by Django 5.1.4 on 2026-07-01 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="course",
            new_name="courses_cou_user_id_225190_idx",
            old_name="courses_cou_user_id_7f0e0d_idx",
        ),
    ]
